name: latex

on:
  push:
    branches: [ master, ci ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: bash compileall.sh
      - uses: actions/upload-artifact@v2
        with:
          name: rendered pdf
          path: main.pdf
